image: pikalab/ci:ubuntu-jdk11-git-gradle-graphviz

before_script:
  - chmod +x gradlew
  - source $HOME/.sdkman/bin/sdkman-init.sh

stages:
  - check
  - build
  - test

Check Code Style and Quality:
  stage: check
  script:
    - gradle ktlintCheck --parallel
    - gradle detekt --parallel
  artifacts:
    paths:
      - "**/build/reports/ktlint/"
  only:
    - branches

Compile:
  stage: build
  script: gradle clean assemble --parallel
  only:
    - branches

Test:
  stage: test
  script: gradle test
  artifacts:
    reports:
      junit: "build/test-results/test/**/TEST-*.xml"
  only:
    - branches