image: pikalab/ci:ubuntu-jdk11-git-gradle-graphviz

before_script:
  - chmod +x gradlew

stages:
  - build
  - test

Compile:
  stage: build
  script: gradle clean assemble --parallel
  only:
    - branches

Test:
  stage: test
  script: gradle test
  artifacts:
    reports:
      junit: "build/test-results/test/**/TEST-*.xml"
  only:
    - branches