comments:
  EndOfSentenceFormat:
    active: true
  UndocumentedPublicClass:
    active: true
    searchInInnerClass: false
  UndocumentedPublicFunction:
    active: true
  UndocumentedPublicProperty:
    active: true
complexity:
  LongMethod:
    active: false
  LongParameterList:
    active: false
  NestedBlockDepth:
    threshold: 5
  TooManyFunctions:
    thresholdInClasses: 18
    thresholdInFiles: 25
    ignoreDeprecated: true
    ignorePrivate: true
    ignoreOverridden: true
    thresholdInInterfaces: 20
    thresholdInObjects: 20
naming:
  MemberNameEqualsClassName:
    active: false
performance:
  SpreadOperator:
    active: false
style:
  ForbiddenComment:
    allowedPatterns: 'TODO:'
  MagicNumber:
    ignoreNumbers: ['-2', '-1', '0', '0.5', '1', '2', '3', '4', '10', '100', '360.0']
  ThrowsCount:
    max: 10